@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ClassMonitorParser" as AddressBookParser LOGIC_COLOR
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant "d:FindCommand" as FindCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find name Alex")
activate LogicManager


LogicManager -> ClassMonitorParser : parseCommand("find name Alex")
activate AddressBookParser

create FindCommandParser
ClassMonitorParser -> FindCommandParser
activate FindCommandParser

FindCommandParser --> ClassMonitorParser
deactivate FindCommandParser

ClassMonitorParser -> FindCommandParser : parse(" name Alex")
activate FindCommandParser

FindCommandParser --> FindCommandParser : parseFindName("Alex")

create NameContainsKeywordPredicate
FindCommandParser -> NameContainsKeywordPredicate
activate NameContainsKeywordPredicate

NameContainsKeywordPredicate --> FindCommandParser
deactivate NameContainsKeywordPredicate

create FindCommand
FindCommandParser -> FindCommand
activate FindCommand

FindCommand --> FindCommandParser :
deactivate FindCommand

FindCommandParser --> ClassMonitorParser : d
deactivate FindCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindCommandParser -[hidden]-> ClassMonitorParser
destroy FindCommandParser
deactivate FindCommandParser


ClassMonitorParser --> LogicManager : d
deactivate ClassMonitorParser

LogicManager -> FindCommand : execute(m)
activate FindCommand

FindCommand -> Model : updateFilteredStudentList(predicate)
activate Model

Model --> FindCommand : Updated filtered student list
deactivate Model

create CommandResult
FindCommand -> CommandResult
activate CommandResult

CommandResult --> FindCommand
deactivate CommandResult

FindCommand --> LogicManager : r
deactivate FindCommand

[<--LogicManager
deactivate LogicManager
@enduml
