@startuml
!pragma useVerticalIf on
start
:User enters sort command;
if () then ([else])
  :Error: Invalid command format;
  stop
( [Field and Direction provided]) elseif () then ([else])
  :Error: Invalid command format;
  stop
( [Valid Field provided]) elseif () then ([else])
  :Error: Invalid command format;
  stop

endif
  :Sort Command successfully executes.The displayed list of
students is updated to be in sorted order of the provided field
in the specified direction;
stop

@enduml
