@startuml
!pragma useVerticalIf on
start
:User enters star command;
if () then ([else])
  :Error: Invalid index provided;
  stop
( [Positive index provided]) elseif () then ([else])
  :Error: Invalid command format;
  stop
( [Number of stars to award provided]) elseif () then ([else])
  :Error: Invalid number of stars provided;
  stop
( [Number of stars to award between 1 and 10 inclusive]) elseif () then ([else])
  :Error: Invalid index provided;
  stop
( [Student index is in valid range of Student List]) elseif () then ([else])
  :Error: Total number of stars invalid;
  stop
else ( [Total number of stars between 0 and 50000 inclusive])
endif
  :Star Command successfully executes.
Student is awarded the number of stars.;
stop

@enduml
