@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "ClassMonitor Storage" #F4F6F6{
Class "<<interface>>\nClassMonitorStorage" as ClassMonitorStorage
Class JsonClassMonitorStorage
Class JsonSerializableClassMonitor
Class JsonAdaptedStudent
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ClassMonitorStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ClassMonitorStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonClassMonitorStorage .up.|> ClassMonitorStorage
JsonClassMonitorStorage ..> JsonSerializableClassMonitor
JsonSerializableClassMonitor --> "*" JsonAdaptedStudent
JsonAdaptedStudent --> "*" JsonAdaptedTag

@enduml
