@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedClassMonitor" as VersionedClassMonitor MODEL_COLOR
end box

[-> Model : undoClassMonitor()
activate Model

Model -> VersionedClassMonitor : undo()
activate VersionedClassMonitor

VersionedClassMonitor -> VersionedClassMonitor :resetData(ReadOnlyClassMonitor)
VersionedClassMonitor --> Model :
deactivate VersionedClassMonitor

[<-- Model
deactivate Model

@enduml
